### ISSUE TITLE
Mounting LIDAR lower

### ISSUE THREAD

**Issue by CrisAdam** [iscumd/Yeti2017#4]
Lidar needs to be mounted securely in a lower position in order to detect moving obstacle

Pending metal sheet to arrive for fabrication

**Comment by CrisAdam** [comment]
Metal sheet is in @DrCurry anything else you need for this?

**Comment by DrCurry** [comment]
LIDAR has been mounted as of Fri 12/30.

**Comment by mikebowyer** [comment]
The LiDAR mount may need to be adjusted to tilt the mount downwards. I took
some ROS bags with the current configuration and the landmarks at the
opposite end of the field could not be seen.

All the best,
Mike Bowyer

Sent from my mobile phone. I apologize for the brevity and any
spelling/grammatical errors.
