### ISSUE TITLE
Replace batteries

### ISSUE THREAD

**Issue by CrisAdam** [iscumd/Yeti2017#5]
Batteries ordered - 2x https://www.batteriesplus.com/productdetails/opt8014=045

**Comment by mikebowyer** [comment]
Ring terminals, lock washers, and bolts for securing wiring to battery terminals have also been ordered.

**Comment by CrisAdam** [comment]
I don't believe we have any 6 gague wire, will we need any?

**Comment by mikebowyer** [comment]
A purchase request was submitted. @eta0920 will need to approve of them.

**Comment by mikebowyer** [comment]
Batteries were delivered.

**Comment by CrisAdam** [comment]
Wires and crimps ordered, pending arrival

**Comment by mikebowyer** [comment]
Wires and Crimps have Arrived.

**Comment by CrisAdam** [comment]
I think this is done
