### ISSUE TITLE
Dual boot Ubuntu & install ROS on Laptop 4

### ISSUE THREAD

**Issue by CrisAdam** [iscumd/Yeti2017#8]
Not sure what the current status is, please update

**Comment by EpicWolverine** [comment]
Is this for laptop 3 (Windows 8.1) or for laptop 4 (Windows 10)?

**Comment by CrisAdam** [comment]
@eta0920 which laptops are we installing ROS on, and in what order? should each be its own task?

**Comment by mikebowyer** [comment]
See tutorial I wrote (Zach, I am on Mikes account) at https://gitlab.com/zdegeorge_umich/ece591/blob/master/documentation/setup/desktop.md

**Comment by EpicWolverine** [comment]
I did this Monday and forgot to close the issue.
